[O2010] Copy backend field so we can compute the frontend one
Proof that migration works upgrading database with existing
account_mtd_vat installation:

$ git stash
$ git checkout mtd-vat-8.0.0.10
$ udc run --rm --service-ports odoo -d mtd-vat -u account_mtd --max-cron-threads=0 --stop-after-init
$ udc exec -u root postgresql psql -U odoo mtd-vat
mtd-vat=# select distinct reconcile, non_mtd_reconcilable from account_account;
ERROR:  column "non_mtd_reconcilable" does not exist
LINE 1: select distinct reconcile, non_mtd_reconcilable from account...
$ git checkout mtd-vat-8.0-standard-reconciliation-issue
$ git stash pop
$ udc run --rm --service-ports odoo -d mtd-vat -u account_mtd --max-cron-threads=0 --stop-after-init
$ udc exec -u root postgresql psql -U odoo mtd-vat
mtd-vat=# select distinct reconcile, non_mtd_reconcilable from account_account;
 reconcile | non_mtd_reconcilable
-----------+----------------------
 f         | f
 t         | t
(2 rows)